// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `collect_cpu_info_inner`, `collect_disks_info_inner`, `collect_memory_info_inner`, `collect_network_info_inner`, `collect_system_info_inner`

/// 一键采集全部深度设备信息
Future<DeepDeviceInfo> collectDeepDeviceInfo() =>
    RustLib.instance.api.crateApiDeviceInfoCollectDeepDeviceInfo();

/// 仅采集系统全局信息
Future<DeepSystemInfo> collectSystemInfoDeep() =>
    RustLib.instance.api.crateApiDeviceInfoCollectSystemInfoDeep();

/// 仅采集 CPU 信息
Future<CpuInfo> collectCpuInfoDeep() =>
    RustLib.instance.api.crateApiDeviceInfoCollectCpuInfoDeep();

/// 仅采集内存信息
Future<MemoryInfo> collectMemoryInfoDeep() =>
    RustLib.instance.api.crateApiDeviceInfoCollectMemoryInfoDeep();

/// 仅采集磁盘信息
Future<List<DiskInfo>> collectDisksInfoDeep() =>
    RustLib.instance.api.crateApiDeviceInfoCollectDisksInfoDeep();

/// 仅采集网络接口信息
Future<List<NetworkInterfaceInfo>> collectNetworkInfoDeep() =>
    RustLib.instance.api.crateApiDeviceInfoCollectNetworkInfoDeep();

/// 单个 CPU 核心的信息
class CoreInfo {
  final String name;
  final BigInt frequencyMhz;
  final double usagePercent;

  const CoreInfo({
    required this.name,
    required this.frequencyMhz,
    required this.usagePercent,
  });

  @override
  int get hashCode =>
      name.hashCode ^ frequencyMhz.hashCode ^ usagePercent.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CoreInfo &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          frequencyMhz == other.frequencyMhz &&
          usagePercent == other.usagePercent;
}

/// CPU 整体信息
class CpuInfo {
  final String arch;
  final String brand;
  final String vendorId;
  final BigInt? physicalCoreCount;
  final BigInt logicalCoreCount;
  final BigInt globalFrequencyMhz;
  final double globalUsagePercent;
  final List<CoreInfo> cores;

  const CpuInfo({
    required this.arch,
    required this.brand,
    required this.vendorId,
    this.physicalCoreCount,
    required this.logicalCoreCount,
    required this.globalFrequencyMhz,
    required this.globalUsagePercent,
    required this.cores,
  });

  @override
  int get hashCode =>
      arch.hashCode ^
      brand.hashCode ^
      vendorId.hashCode ^
      physicalCoreCount.hashCode ^
      logicalCoreCount.hashCode ^
      globalFrequencyMhz.hashCode ^
      globalUsagePercent.hashCode ^
      cores.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CpuInfo &&
          runtimeType == other.runtimeType &&
          arch == other.arch &&
          brand == other.brand &&
          vendorId == other.vendorId &&
          physicalCoreCount == other.physicalCoreCount &&
          logicalCoreCount == other.logicalCoreCount &&
          globalFrequencyMhz == other.globalFrequencyMhz &&
          globalUsagePercent == other.globalUsagePercent &&
          cores == other.cores;
}

/// 聚合所有深度设备信息的顶层结构体
class DeepDeviceInfo {
  final DeepSystemInfo system;
  final CpuInfo cpu;
  final MemoryInfo memory;
  final List<DiskInfo> disks;
  final List<NetworkInterfaceInfo> networkInterfaces;

  const DeepDeviceInfo({
    required this.system,
    required this.cpu,
    required this.memory,
    required this.disks,
    required this.networkInterfaces,
  });

  @override
  int get hashCode =>
      system.hashCode ^
      cpu.hashCode ^
      memory.hashCode ^
      disks.hashCode ^
      networkInterfaces.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeepDeviceInfo &&
          runtimeType == other.runtimeType &&
          system == other.system &&
          cpu == other.cpu &&
          memory == other.memory &&
          disks == other.disks &&
          networkInterfaces == other.networkInterfaces;
}

/// 系统全局信息
class DeepSystemInfo {
  final String hostName;
  final String osName;
  final String osVersion;
  final String kernelVersion;
  final String distributionId;
  final BigInt uptimeSeconds;
  final BigInt bootTimeUnix;
  final double loadAverageOne;
  final double loadAverageFive;
  final double loadAverageFifteen;

  const DeepSystemInfo({
    required this.hostName,
    required this.osName,
    required this.osVersion,
    required this.kernelVersion,
    required this.distributionId,
    required this.uptimeSeconds,
    required this.bootTimeUnix,
    required this.loadAverageOne,
    required this.loadAverageFive,
    required this.loadAverageFifteen,
  });

  @override
  int get hashCode =>
      hostName.hashCode ^
      osName.hashCode ^
      osVersion.hashCode ^
      kernelVersion.hashCode ^
      distributionId.hashCode ^
      uptimeSeconds.hashCode ^
      bootTimeUnix.hashCode ^
      loadAverageOne.hashCode ^
      loadAverageFive.hashCode ^
      loadAverageFifteen.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeepSystemInfo &&
          runtimeType == other.runtimeType &&
          hostName == other.hostName &&
          osName == other.osName &&
          osVersion == other.osVersion &&
          kernelVersion == other.kernelVersion &&
          distributionId == other.distributionId &&
          uptimeSeconds == other.uptimeSeconds &&
          bootTimeUnix == other.bootTimeUnix &&
          loadAverageOne == other.loadAverageOne &&
          loadAverageFive == other.loadAverageFive &&
          loadAverageFifteen == other.loadAverageFifteen;
}

/// 单个挂载点的磁盘信息
class DiskInfo {
  final String name;
  final String mountPoint;
  final BigInt totalBytes;
  final BigInt availableBytes;
  final double usagePercent;
  final String fileSystem;
  final String diskType;
  final bool isRemovable;

  const DiskInfo({
    required this.name,
    required this.mountPoint,
    required this.totalBytes,
    required this.availableBytes,
    required this.usagePercent,
    required this.fileSystem,
    required this.diskType,
    required this.isRemovable,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      mountPoint.hashCode ^
      totalBytes.hashCode ^
      availableBytes.hashCode ^
      usagePercent.hashCode ^
      fileSystem.hashCode ^
      diskType.hashCode ^
      isRemovable.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DiskInfo &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          mountPoint == other.mountPoint &&
          totalBytes == other.totalBytes &&
          availableBytes == other.availableBytes &&
          usagePercent == other.usagePercent &&
          fileSystem == other.fileSystem &&
          diskType == other.diskType &&
          isRemovable == other.isRemovable;
}

/// 内存信息（含交换分区）
class MemoryInfo {
  final BigInt totalBytes;
  final BigInt usedBytes;
  final BigInt freeBytes;
  final BigInt availableBytes;
  final double usagePercent;
  final BigInt swapTotalBytes;
  final BigInt swapUsedBytes;
  final BigInt swapFreeBytes;

  const MemoryInfo({
    required this.totalBytes,
    required this.usedBytes,
    required this.freeBytes,
    required this.availableBytes,
    required this.usagePercent,
    required this.swapTotalBytes,
    required this.swapUsedBytes,
    required this.swapFreeBytes,
  });

  @override
  int get hashCode =>
      totalBytes.hashCode ^
      usedBytes.hashCode ^
      freeBytes.hashCode ^
      availableBytes.hashCode ^
      usagePercent.hashCode ^
      swapTotalBytes.hashCode ^
      swapUsedBytes.hashCode ^
      swapFreeBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MemoryInfo &&
          runtimeType == other.runtimeType &&
          totalBytes == other.totalBytes &&
          usedBytes == other.usedBytes &&
          freeBytes == other.freeBytes &&
          availableBytes == other.availableBytes &&
          usagePercent == other.usagePercent &&
          swapTotalBytes == other.swapTotalBytes &&
          swapUsedBytes == other.swapUsedBytes &&
          swapFreeBytes == other.swapFreeBytes;
}

/// 单个网络接口的信息
class NetworkInterfaceInfo {
  final String name;
  final String macAddress;
  final List<String> ipAddresses;
  final BigInt totalReceivedBytes;
  final BigInt totalTransmittedBytes;

  const NetworkInterfaceInfo({
    required this.name,
    required this.macAddress,
    required this.ipAddresses,
    required this.totalReceivedBytes,
    required this.totalTransmittedBytes,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      macAddress.hashCode ^
      ipAddresses.hashCode ^
      totalReceivedBytes.hashCode ^
      totalTransmittedBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NetworkInterfaceInfo &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          macAddress == other.macAddress &&
          ipAddresses == other.ipAddresses &&
          totalReceivedBytes == other.totalReceivedBytes &&
          totalTransmittedBytes == other.totalTransmittedBytes;
}
